### PR TITLE
Update role to support mongodb 7.x

### PR DESCRIPTION
**Pull request by NikonNLG**
Also, removed unsupported parameters in fresh ansible

### CODE REVIEW

**Comment by csuka** [comment]
lgtm

**Comment by NikonNLG** [comment]
@csuka thanks.
Do you mind if I'll update role to be more ansible-lint compatible?
Now it show something like this:
```
                    Rule Violation Summary
 count tag               profile    rule associated tags
     8 key-order[task]   basic      formatting
     7 jinja[spacing]    basic      formatting (warning)
     1 schema[meta]      basic      core
    14 name[missing]     basic      idiom
    88 name[casing]      moderate   idiom
     7 no-changed-when   shared     command-shell, idempotency
    88 fqcn[action-core] production formatting

Failed: 206 failure(s), 7 warning(s) on 17 files. Last profile that met the validation criteria was 'min'.
```

**Comment by csuka** [comment]
You could try, but just so you know, they're just guidelines.
When I look at my code, i prefer it the way it is. It's looks clean.

E.g. 'no changed when', i don't care, i most likely put it there for a reason.
E.g. 'fqcn', i don't care. I prefer not to use fqcn actually.

But go wild, and i'll provide a review.
Ensure to take the [current .ansible-lint](https://github.com/csuka/ansible_role_mongodb/blob/main/.ansible-lint) file into account.

**Comment by NikonNLG** [comment]
No worries then! Just want to check, maybe you want to fix it but doesn't have free time.
Ok, I'll keep it as it is

**Pull request merged**
